@WebApiLab_API_HostAddress = http://localhost:5195

GET {{WebApiLab_API_HostAddress}}/people
Accept: application/json

###

GET {{WebApiLab_API_HostAddress}}/api/People/V59OF92YF627HFY0
Accept: application/json